### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by aubreywullschleger** [oforir/prj-rev-bwfs-dasmoto#1]
### Criteria 1: HTML and CSS Linking  
* _Score Level:_ 4
* _Comment(s):_ HTML file contains a valid link to the correct CSS file.
 
### Criteria 2: Implementation of Design Specification and Content
* _Score Level:_ 4
* _Comment(s):_ The page includes all styles and content provided in the design specification.
 
### Criteria 3: HTML Elements and Content
* _Score Level:_ 4
* _Comment(s):_ Content: HTML content matches the design specification

Tags: The tags in the HTML are used for their intended purpose.

### Criteria 4: CSS Selectors and Syntax
* _Score Level:_ 4
* _Comment(s):_ Syntax: Uses proper selectors (id, class, element type). All rule sets are valid CSS.
 
### Overall Score: 16/16
Grade: Exceeds expectations

Summary:
Wonderful job on this first project!  I like your organized HTML, your use of `<div>` elements to wrap the different sections of your page,  your use of descriptive `alt` attributes for your `<img>` elements, and that your CSS is following the DRY principle with the use of inheritance and element/class selectors.

One thing to work on - try implementing more semantic HTML elements if/when you refactor this project (and in future projects!)

Next, as a stretch goal, I challenge you to research and implement media queries to make your page responsive for all screen widths. This is a challenge I think you are ready for based on your work here! Here are a couple resources to get you started: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries and https://css-tricks.com/snippets/css/media-queries-for-standard-devices/

**Comment by oforir** [comment]
Dear aubreywullschleger,

Thank you very much for reviewing my project so swiftly. I very much appreciate your feedback and the various reading suggestions, I have added those to my reading list. 

Kind regards,
Reginald
