### ISSUE TITLE
DRY CSS

### ISSUE THREAD

**Issue by aubreywullschleger** [oforir/prj-rev-bwfs-dasmoto#2]
Great! Nice use of the `html` selector in your CSS. The use of the `html` selector helps keep your CSS concise especially when using inherited styles on the selector as you've done with `font-family: "Helvetica";` here.

https://github.com/oforir/prj-rev-bwfs-dasmoto/blob/master/Project1_Dasmoto/resources/css/style.css#L4-L6

I also like your use of the `span` and `.h2-header` selectors to style multiple elements at the same time - great implementation of the DRY (Don't Repeat Yourself) principle here!

**Comment by oforir** [comment]
Tx!
