### ISSUE TITLE
Alt attributes

### ISSUE THREAD

**Issue by aubreywullschleger** [oforir/prj-rev-bwfs-dasmoto#3]
Great! I like that you've used descriptive `alt` attributes on your `<img>` elements as this is best practice and helps your site to be more accessible! For future projects, note that we can leave `alt` attributes empty (`alt=""`), but should not omit them entirely, when the image does not add information to the content of the page. See this resource to help aid in your decision to give `alt` attribute values (or to leave them empty): https://www.w3.org/WAI/tutorials/images/decorative/

Example: https://github.com/oforir/prj-rev-bwfs-dasmoto/blob/master/Project1_Dasmoto/index.html#L36

**Comment by oforir** [comment]
Aha, lesson learned! Thank you!
