### ISSUE TITLE
Nesting and indentation

### ISSUE THREAD

**Issue by aubreywullschleger** [oforir/prj-rev-bwfs-dasmoto#5]
Great! Nice work with the consistent nesting and indentation in your HTML.  I also appreciate your use of comments before each section. Here's more info on best practices for nesting and indentation (and other HTML/CSS best practices) to use in future/more complex projects: https://learn.shayhowe.com/html-css/writing-your-best-code/. These practices help with the organization and readability of your markup.

Example:  https://github.com/oforir/prj-rev-bwfs-dasmoto/blob/master/Project1_Dasmoto/index.html#L12-L40

**Comment by oforir** [comment]
Thank you!
